name: build
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - name: Yandex Cloud CR "Login" Action for GitHub Actions
        uses: yc-actions/yc-cr-login@v0.1-alpha
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
      - name: Build, tag, and push image to Yandex Cloud Container Registry
        env:
          CR_REGISTRY: crpqhtbgo1oa3o9noecv
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t cr.yandex/$CR_REGISTRY/cursor-tracker:$IMAGE_TAG .
          docker push cr.yandex/$CR_REGISTRY/cursor-tracker:$IMAGE_TAG

      - name: Deploy Serverless Container
        env:
          CR_REGISTRY: crpqhtbgo1oa3o9noecv
          IMAGE_TAG: ${{ github.sha }}
        id: deploy-sls-container
        uses: yc-actions/yc-sls-container-deploy@v2
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          folder-id:  ${{ secrets.YANDEX_FOLDER_ID }}
          container-name: cursor-tracker
          revision-service-account-id: cursor-tracker
          revision-cores: 1
          revision-memory: 128
          revision-core-fraction: 20
          revision-concurrency: 1
          revision-image-url: cr.yandex/$CR_REGISTRY/cursor-tracker:$IMAGE_TAG
          revision-execution-timeout: 10